version: '3.8'

services:
  go-greeter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
