version: '3.8'

services:
  django-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
